name: mlflow-env
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - pip
  - pip:
      - mlflow
      - influxdb
      - jupyter
      - statsmodels
      - xgboost