name: mlflow-tensorflow
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - tensorflow=2.10.0   # 添加 TensorFlow
  - pip
  - pip:
      - mlflow
      - influxdb
      - jupyter
      - statsmodels
      - xgboost