version: '3'
services:
  mlflow:
    build: ./mlflow-server
    ports:
      - "5001:5000"  
    volumes:
      - ./mlruns:/mlflow/mlruns 
    command: >
      mlflow server
      --backend-store-uri /mlflow/mlruns
      --default-artifact-root /mlflow/mlruns
      --host 0.0.0.0
      --port 5000
      --workers 1

  fastapi:
    build: ./fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    environment:
      # 如果用的是 compose，容器之间通信可用 service 名
      - USE_LOCAL_MLFLOW=false
      - MLFLOW_TRACKING_URI=http://mlflow:5000

    volumes:
      # 如果 FastAPI 使用本地模型，才挂载
       - ./mlruns:/app/mlruns 