name: Deploy to Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd /home/bowen/short-time-wind-energy-forecasting-system
            git pull origin master
            docker build -f fastapi-app/Dockerfile -t wind-api .
            docker stop wind-api || true
            docker rm wind-api || true
            docker run -d --name wind-api -p 8000:8000 wind-api
          EOF